export const NEXT_PAGE = "NEXT_PAGE";
export const BACK_PAGE = "BACK_PAGE";

export const INPUT_CHANGE = "INPUT_CHANGE";
export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
export const FETCH_ADDRESSES_SUCCESS = "FETCH_ADDRESSES_SUCCESS";
export const FETCH_ADDRESSES_FAILED = "FETCH_ADDRESSES_FAILED";

export const VALIDATE_ACTIVITY_FIELD = "VALIDATE_ACTIVITY_FIELD";
export const VALIDATE_ADDRESS_FIELD = "VALIDATE_ADDRESS_FIELD";

export const NEXT_ADDRESS = "NEXT_ADDRESS";
